#:import menu menu

MainWidget:

<MainWidget>:
    canvas.before:
        Rectangle:
            id: jungle_background
            size: self.width, self.height
            source: root.displayed_image
    menu_widget: menu_widget
    perspective_point_x: self.width/2
    perspective_point_y: self.height*0.75
    MenuWidget:
        id: menu_widget
    Label:
        text: root.score_txt
        font_size: dp(15)
        font_name: 'fonts/Eurostile.ttf'
        pos: 0, 325
